@startmindmap
* APP
** 主页面
*** 正常显示HomePage
*** 正常显示Transfer
*** 正常显示MePage
**** 未登录：展示登录按钮
**** 已登录：展示用户手机号和用户名
** 登录
*** 输入手机号密码登录
**** 手机号
***** 手机长度>=5
***** 手机长度<5
**** 密码
***** 密码长度>=5
***** 密码长度<5
*** 输入PIN code
*** 获取用户信息
*** 正确保存用户信息
@endmindmap
